import type { Environment, SecretExportMode } from '../../shared/types/request';

function slug(name: string): string { return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }

function yamlEscape(v: string): string {
  if (v.includes('\n') || v.includes(':') || v.includes('#') || v.startsWith(' ') || v === '' ) return JSON.stringify(v);
  return v;
}

function toYaml(env: Environment, secretMode: SecretExportMode): string {
  const lines: string[] = [];
  lines.push(`name: ${yamlEscape(env.name)}`);
  if (env.description) lines.push(`description: ${yamlEscape(env.description)}`);
  if (env.color) lines.push(`color: "${env.color}"`);
  lines.push(`schema_version: "${env.schema_version ?? '1.0'}"`);
  lines.push('meta:');
  lines.push(`  id: "${env.id}"`);
  lines.push(`  created: "${env.meta?.created ?? new Date().toISOString()}"`);
  lines.push(`  modified: "${new Date().toISOString()}"`);
  lines.push(`  source: "${env.meta?.source ?? 'native'}"`);
  if (env.meta?.imported_from) lines.push(`  imported_from: "${env.meta.imported_from}"`);
  lines.push('variables:');
  for (const v of env.variables) {
    if (secretMode === 'omit' && v.type === 'secret') continue;
    let val = v.value;
    if (v.type === 'secret' && secretMode === 'encrypted' && !val.startsWith('KEYRING_REF:')) {
      // reference kept as is; caller should have encrypted before
      val = `KEYRING_REF:${v.id}`;
    }
    lines.push(`  - key: ${yamlEscape(v.key)}`);
    lines.push(`    value: ${yamlEscape(val)}`);
    lines.push(`    type: ${v.type}`);
    lines.push(`    enabled: ${v.enabled !== false}`);
    if (v.description) lines.push(`    description: ${yamlEscape(v.description)}`);
  }
  return lines.join('\n') + '\n';
}

function toPostman(env: Environment, secretMode: SecretExportMode): string {
  const values = env.variables
    .filter(v => !(secretMode === 'omit' && v.type === 'secret'))
    .map(v => ({
      key: v.key,
      value: v.type === 'secret' && secretMode === 'encrypted' ? `KEYRING_REF:${v.id}` : v.value,
      type: v.type === 'secret' ? 'secret' : 'default',
      enabled: v.enabled !== false,
    }));
  return JSON.stringify({
    id: env.id,
    name: env.name,
    values,
    _postman_variable_scope: 'environment',
    _export_format: '2.1',
  }, null, 2);
}

function toDotenv(env: Environment, secretMode: SecretExportMode): string {
  const lines: string[] = [
    `# Generated by APIForge v1.0`,
    `# Environment: ${env.name}`,
    `# Exported: ${new Date().toISOString()}`,
    '',
  ];
  for (const v of env.variables) {
    if (secretMode === 'omit' && v.type === 'secret') continue;
    if (!v.enabled) continue;
    const val = v.type === 'secret' && secretMode === 'encrypted' ? `KEYRING_REF:${v.id}` : v.value;
    // escape value if contains spaces/newlines
    const escaped = /[\s#]/.test(val) ? `"${val.replace(/"/g, '\\"')}"` : val;
    lines.push(`${v.key}=${escaped}`);
  }
  return lines.join('\n') + '\n';
}

function toJsonKv(env: Environment, secretMode: SecretExportMode): string {
  const vars: Record<string, any> = {};
  for (const v of env.variables) {
    if (secretMode === 'omit' && v.type === 'secret') continue;
    let val: any = v.value;
    if (v.type === 'secret' && secretMode === 'encrypted') val = `KEYRING_REF:${v.id}`;
    else if (v.type === 'number') val = Number(val);
    else if (v.type === 'boolean') val = val.toLowerCase() === 'true';
    vars[v.key] = val;
  }
  return JSON.stringify({
    _meta: { name: env.name, exported_at: new Date().toISOString(), tool: 'APIForge v1.0', color: env.color, description: env.description },
    variables: vars,
  }, null, 2);
}

function toCsv(env: Environment, secretMode: SecretExportMode): string {
  const lines: string[] = ['key,value,type,enabled,description'];
  const esc = (s: string) => `"${String(s).replace(/"/g, '""')}"`;
  for (const v of env.variables) {
    if (secretMode === 'omit' && v.type === 'secret') continue;
    const val = v.type === 'secret' && secretMode === 'encrypted' ? `KEYRING_REF:${v.id}` : v.value;
    lines.push([esc(v.key), esc(val), esc(v.type), esc(String(v.enabled !== false)), esc(v.description ?? '')].join(','));
  }
  return lines.join('\n') + '\n';
}

export type EnvExportFormat = 'yaml' | 'postman' | 'dotenv' | 'json' | 'csv';

export function exportEnvironment(env: Environment, format: EnvExportFormat, secretMode: SecretExportMode = 'encrypted'): { content: string; filename: string; mime: string } {
  switch (format) {
    case 'yaml': return { content: toYaml(env, secretMode), filename: `${slug(env.name)}.env.yaml`, mime: 'text/yaml' };
    case 'postman': return { content: toPostman(env, secretMode), filename: `${slug(env.name)}.postman_environment.json`, mime: 'application/json' };
    case 'dotenv': return { content: toDotenv(env, secretMode), filename: `.env.${slug(env.name)}`, mime: 'text/plain' };
    case 'json': return { content: toJsonKv(env, secretMode), filename: `${slug(env.name)}.env.json`, mime: 'application/json' };
    case 'csv': return { content: toCsv(env, secretMode), filename: `${slug(env.name)}.env.csv`, mime: 'text/csv' };
    default: throw new Error(`Unsupported export format: ${format}`);
  }
}

// collection exporters reuse existing pdf-exporter etc; add light wrappers here for yaml native
export function exportCollectionYaml(collection: any): string {
  const lines: string[] = [];
  lines.push(`name: ${JSON.stringify(collection.name)}`);
  lines.push(`schema_version: "1.0"`);
  lines.push(`variables: []`);
  return lines.join('\n');
}
